"""Generate English narration with Kokoro-82M (local, Apache-2.0), trim, loudness-match, encode to OGG."""
import subprocess, sys, json
from pathlib import Path
import numpy as np, soundfile as sf, pyloudnorm as pyln
from kokoro_onnx import Kokoro

ROOT = Path(__file__).resolve().parent.parent
FFMPEG = ROOT / "tools/ffmpeg/bin/ffmpeg.exe"
LINES = {
    "vo-welcome": "Let's cook!",
    "vo-pick-pizza": "Let's make a pizza!",
    "vo-roll": "Roll the dough!",
    "vo-sauce": "Spread the sauce!",
    "vo-cheese": "Sprinkle the cheese!",
    "vo-toppings": "Add your toppings!",
    "vo-done-hint": "Tap when you're done!",
    "vo-oven": "Into the oven!",
    "vo-baking": "It's baking!",
    "vo-ready": "Ding! It's ready!",
    "vo-feed": "Time to eat!",
    "vo-praise-1": "Great job!",
    "vo-praise-2": "Wow!",
    "vo-praise-3": "Beautiful!",
    "vo-praise-4": "Yummy!",
    "vo-finale": "You made a pizza!",
}
VOICES = {"voice-a": ("af_heart", 0.85), "voice-b": ("af_bella", 0.85)}

# Mom script (python make_vo.py mom): Mom narrates next to her daughter; Pipa the hedgehog tastes at the end.
# Spoken text may differ from the script only by punctuation, used to steer Kokoro's intonation.
MOM_LINES = {
    "vo-welcome": "Let's cook together!",
    "vo-pick-pizza": "Let's make a pizza!",
    "vo-watch-me": "Watch me first!",
    "vo-your-turn": "Now, you try!",
    "vo-roll": "Let's roll the dough!",
    "vo-sauce": "Now spread the sauce!",
    "vo-cheese": "Sprinkle the cheese!",
    "vo-toppings": "Put on anything you like!",
    "vo-done-hint": "Tap here when you're done!",
    "vo-oven": "Into the oven it goes!",
    "vo-baking": "Look, it's baking!",
    "vo-ready": "Ding! It's ready!",
    "vo-feed": "Let's give Pipa a taste!",
    "vo-help": "Let me help you!",
    "vo-praise-1": "Great job!",
    "vo-praise-2": "Wow!",
    "vo-praise-3": "Beautiful!",
    "vo-praise-4": "Yummy!",
    "vo-praise-5": "I love it!",
    "vo-praise-6": "You worked so hard!",
    "vo-praise-7": "I love how you did that!",
    "vo-finale": "We made a pizza together!",
    "vo-bye": "That was fun! Bye bye!",
    # Prep steps (added 2026-09-19; Voice A only: python make_vo.py mom-a)
    "vo-hello": "Hi! I'm so happy to cook with you today!",
    "vo-what-make": "What shall we make today?",
    "vo-wash": "First, let's wash our hands!",
    "vo-wash-rub": "Rub, rub, rub!",
    "vo-wash-done": "All clean!",
    "vo-knead": "Let's squish the dough!",
    "vo-crush": "Squish the tomatoes!",
    "vo-stir": "Now stir it all around!",
    "vo-grate": "Let's grate the cheese!",
    "vo-choose": "Pick three toppings you like!",
    "vo-cut": "Let's cut it together!",
    "vo-cut-careful": "Nice and slow. Careful fingers!",
    "vo-open-can": "Let's open the can!",
    "vo-open-jar": "Let's open the jar!",
    "vo-pour": "Pour it into the bowl!",
    "vo-temp": "Let's set the oven to two hundred!",
    "vo-temp-more": "A little more!",
    "vo-temp-hot": "Oops, too hot! Turn it down a little.",
    "vo-temp-done": "Perfect! Now press start!",
    "vo-mitts": "It's hot! Put on your oven mitts!",
    "vo-share": "Let's share the pizza!",
    "vo-slice-mom": "One for me? Thank you!",
    "vo-mom-yum": "Mmm, delicious!",
    "vo-slice-pipa": "One for Pipa!",
    "vo-photo": "Let's take a picture of your pizza!",
    # Counting while cutting (played in quick succession)
    "count-1": "One!",
    "count-2": "Two!",
    "count-3": "Three!",
    "count-4": "Four!",
    "count-5": "Five!",
    "count-6": "Six!",
    "count-7": "Seven!",
    "count-8": "Eight!",
    "count-9": "Nine!",
    "count-10": "Ten!",
    # Oven temperature (played on every tap of the dial)
    "temp-50": "Fifty!",
    "temp-100": "One hundred!",
    "temp-150": "One hundred fifty!",
    "temp-200": "Two hundred!",
    "temp-250": "Two hundred fifty!",
    # Salad (second recipe, added 2026-09-19; Voice A only: python make_vo.py mom-a <names>)
    "vo-pick-salad": "Let's make a salad!",
    "vo-wash-veg": "Let's wash the vegetables!",
    "vo-wash-veg-done": "Squeaky clean!",
    "vo-tear": "Tear the lettuce into little pieces!",
    "vo-choose-veg": "Pick three vegetables you like!",
    "vo-into-bowl": "Put it all in the bowl!",
    "vo-squeeze": "Squeeze the lemon!",
    "vo-oil": "Pour a little olive oil!",
    "vo-salt": "A tiny pinch of salt!",
    "vo-mix": "Now mix it all up!",
    "vo-serve": "Let's serve the salad!",
    "vo-bowl-mom": "Some for me? Thank you!",
    "vo-bowl-pipa": "Some for Pipa!",
    "vo-fresh": "Mmm, so fresh and crunchy!",
    "vo-photo-salad": "Let's take a picture of your salad!",
    "vo-finale-salad": "We made a salad together!",
    # Ingredient names (said when the child picks one; may cut each other off)
    "name-cucumber": "Cucumber!",
    "name-tomato": "Tomato!",
    "name-pepper": "Pepper!",
    "name-carrot": "Carrot!",
    "name-onion": "Onion!",
    "name-lettuce": "Lettuce!",
    "name-mushroom": "Mushroom!",
    "name-corn": "Corn!",
    "name-olives": "Olives!",
    "name-lemon": "Lemon!",
    # Cookies (third recipe, added 2026-09-19; Voice A only: python make_vo.py mom-a <names>)
    "vo-pick-cookies": "Let's bake cookies!",
    "vo-flour": "Pour in the flour!",
    "vo-sugar": "Now the sugar!",
    "vo-butter": "Drop in the butter!",
    "vo-egg": "Crack the egg! Tap, tap, tap!",
    "vo-stir-dough": "Stir it into dough!",
    "vo-knead-cookies": "Let's squish the cookie dough!",
    "vo-roll-cookies": "Roll it nice and flat!",
    "vo-pick-cutter": "Pick a shape you like!",
    "vo-stamp": "Press it into the dough!",
    "name-star": "A star!",
    "name-heart": "A heart!",
    "name-circle": "A circle!",
    "name-flower": "A flower!",
    "vo-tray": "Onto the baking tray!",
    "vo-temp-150": "Let's set the oven to one hundred fifty!",
    "vo-decorate-cookies": "Decorate them any way you like!",
    "vo-share-cookies": "Let's share the cookies!",
    "vo-cookie-mom": "A cookie for me? Thank you!",
    "vo-cookie-pipa": "A cookie for Pipa!",
    "vo-cookie-yum": "Mmm, so sweet and crumbly!",
    "vo-photo-cookies": "Let's take a picture of your cookies!",
    "vo-finale-cookies": "We made cookies together!",
    # Fruit smoothie (fourth recipe, added 2026-09-19; Voice A only: python make_vo.py mom-a <names>)
    "vo-pick-smoothie": "Let's make a smoothie!",
    "vo-wash-fruit": "Let's wash the fruit!",
    "vo-choose-fruit": "Pick three fruits you like!",
    "name-banana": "Banana!",
    "name-strawberry": "Strawberry!",
    "name-mango": "Mango!",
    "name-kiwi": "Kiwi!",
    "vo-into-blender": "Put it all in the blender!",
    "vo-milk": "Pour in the milk!",
    "vo-lid": "Put the lid on tight!",
    "vo-blend": "Press the big button!",
    "vo-blend-done": "All smooth!",
    "vo-pour-glass": "Pour it into the glasses!",
    "vo-share-smoothie": "Let's share the smoothie!",
    "vo-glass-mom": "A glass for me? Thank you!",
    "vo-glass-pipa": "A glass for Pipa!",
    "vo-smoothie-yum": "Mmm, so fruity and cold!",
    "vo-photo-smoothie": "Let's take a picture of your smoothie!",
    "vo-finale-smoothie": "We made a smoothie together!",
    # Pancakes (fifth recipe, added 2026-09-19; Voice A only: python make_vo.py mom-a <names>)
    "vo-pick-pancakes": "Let's make pancakes!",
    "vo-stir-batter": "Stir the batter nice and smooth!",
    "vo-stove": "Let's turn on the stove!",
    "vo-ladle": "Pour the batter into the pan!",
    "vo-bubbles": "Wait for the bubbles!",
    "vo-flip": "Now flip it! Swipe up!",
    "vo-flip-done": "Whee! Golden brown!",
    "vo-more-pancake": "One more!",
    "vo-decorate-pancakes": "Put on anything you like!",
    "vo-share-pancakes": "Let's share the pancakes!",
    "vo-pancake-mom": "Some for me? Thank you!",
    "vo-pancake-pipa": "Some for Pipa!",
    "vo-pancake-yum": "Mmm, warm and fluffy!",
    "vo-photo-pancakes": "Let's take a picture of your pancakes!",
    "vo-finale-pancakes": "We made pancakes together!",
    # Vegetable soup (sixth recipe, added 2026-09-20; Voice A only: python make_vo.py mom-a <names>)
    "vo-album": "Look at everything we made!",
    "vo-pick-soup": "Let's make vegetable soup!",
    "name-potato": "Potato!",
    "name-zucchini": "Zucchini!",
    "vo-peel": "Let's peel it! Swipe along!",
    "vo-peel-done": "All peeled!",
    "vo-into-pot": "Put it all in the pot!",
    "vo-water": "Pour in the water!",
    "vo-stir-soup": "Stir the soup while it cooks!",
    "vo-soup-ready": "It smells so good!",
    "vo-serve-soup": "Let's serve the soup!",
    "vo-soup-mom": "A bowl for me? Thank you!",
    "vo-soup-pipa": "A bowl for Pipa!",
    "vo-soup-yum": "Mmm, warm and cozy!",
    "vo-photo-soup": "Let's take a picture of your soup!",
    "vo-finale-soup": "We made soup together!",
    # Birthday cake (seventh recipe, added 2026-09-20; Voice A only: python make_vo.py mom-a <names>)
    "vo-pick-cake": "Let's bake a birthday cake!",
    "vo-stir-cake": "Stir the cake batter!",
    "vo-pour-pan": "Pour it into the pan!",
    "vo-pick-frosting": "Pick a frosting color!",
    "name-pink": "Pink!",
    "name-white": "White!",
    "name-chocolate": "Chocolate!",
    "vo-frost": "Spread the frosting all over!",
    "vo-decorate-cake": "Decorate your cake!",
    "vo-candles": "Put on the candles!",
    "vo-wish": "Make a wish and blow out the candles!",
    "vo-blow-more": "Keep blowing!",
    "vo-blown": "Yay! Happy birthday!",
    "vo-share-cake": "Let's share the cake!",
    "vo-cake-mom": "A slice for me? Thank you!",
    "vo-cake-pipa": "A slice for Pipa!",
    "vo-cake-yum": "Mmm, so soft and sweet!",
    "vo-photo-cake": "Let's take a picture of your cake!",
    "vo-finale-cake": "We made a birthday cake together!",
    # Fruit skewers (eighth recipe, added 2026-09-25; the thread step: copy, extend, create a pattern)
    "vo-pick-skewers": "Fruit skewers! Yummy!",
    "vo-thread": "Let's slide the fruit onto the stick!",
    "vo-copy": "Look at mine! Can you make one just like it?",
    "vo-same": "Just like mine!",
    "vo-next": "What comes next?",
    "vo-pattern": "You found the pattern!",
    "vo-new-pattern": "Ooh! A brand new pattern!",
    "vo-own": "Now make your very own!",
    "vo-share-skewers": "Let's share our fruit skewers!",
    "vo-skewer-mom": "A skewer for me? Thank you!",
    "vo-skewer-pipa": "One for Pipa!",
    "vo-skewer-yum": "Mmm, so juicy!",
    "vo-photo-skewers": "Let's take a picture of our fruit skewers!",
    "vo-finale-skewers": "We made fruit skewers together!",
    # Gameplay round (added 2026-09-25; Voice A only: python make_vo.py mom-a <names>): Pipa's wishes and tastes
    "vo-pipa-wants": "Look! Pipa wants...",
    "vo-pipa-got-it": "Just what Pipa wanted!",
    "vo-pipa-loves": "Pipa loves it!",
    "vo-bless-you": "Bless you, Pipa!",
    # the guests round: who comes to eat with Mom and Pipa
    "vo-guest-who": "Who's coming to eat with us?",
    "vo-pipa-brought": "Pipa brought a friend!",
    "vo-guest-giraffe": "Look, Giraffe is here!",
    "vo-guest-turtle": "Look, Turtle is here!",
    "vo-guest-penguin": "Look, Penguin is here!",
    "vo-for-giraffe": "Some for Giraffe!",
    "vo-for-turtle": "Some for Turtle!",
    "vo-for-penguin": "Some for Penguin!",
    "vo-giraffe-loves": "Giraffe loves green food!",
    "vo-turtle-loves": "Turtle loves it!",
    "vo-penguin-loves": "Penguin loves it!",
    "vo-turtle-nap": "Shh! Turtle is having a little nap.",
    "vo-bless-penguin": "Bless you, Penguin!",
    "vo-pull-out": "Now pull it out, nice and slow!",
    "vo-cut-slices": "Let's cut it into slices!",
    # The puzzle (added 2026-09-26; Voice A only: python make_vo.py mom-a <names>): a picture from the memory book
    "vo-puzzle": "Let's make a puzzle from your picture!",
    "vo-puzzle-done": "You put it all together!",
    # The garden (added 2026-09-26; Voice A only: python make_vo.py mom-a <names>): plant, water, grow, pick
    "vo-pick-garden": "Let's go to the garden!",
    "vo-garden-seeds": "What shall we grow? Pick some seeds!",
    "vo-garden-plant": "Put a seed in each little hole!",
    "vo-garden-water": "Now let's water them!",
    "vo-garden-sprout": "Look! They're growing!",
    "vo-garden-cloud": "Oh, a cloud! Can you push it away?",
    "vo-garden-sun": "Hello, sunshine!",
    "vo-garden-snail": "A hungry snail! Let's give it a leaf.",
    "vo-garden-snail-yum": "Munch, munch! The snail is happy.",
    "vo-garden-pick": "Let's pick them! Into the basket!",
    "vo-garden-pull": "Let's pull the carrots out!",
    "vo-garden-done": "What a lovely harvest! We grew it together!",
    # Gameplay round 4 (added 2026-09-26; Voice A only: python make_vo.py mom-a <names>): find the tool, Pipa's order,
    # stir with the arrow
    "vo-find-grater": "Which one is the grater? Can you find it?",
    "vo-find-pin": "Which one is the rolling pin? Can you find it?",
    "vo-find-spoon": "Which one is the wooden spoon? Can you find it?",
    "name-grater": "Grater!",
    "name-rolling-pin": "Rolling pin!",
    "name-spoon": "Spoon!",
    "name-whisk": "Whisk!",
    "name-spatula": "Spatula!",
    "vo-pipa-order": "Look! Pipa wants two things, in order. First...",
    "vo-then": "and then...",
    "vo-first-this": "Pipa wants this one first!",
    "vo-stir-arrow": "Stir round and round, the way the arrow goes!",
    "vo-other-way": "Now stir the other way!",
    # Two mini-games (added 2026-09-28; Voice A only: python make_vo.py mom-a <names>): the market, washing up
    "vo-pick-market": "Let's go to the market!",
    "vo-market-list": "Here's our shopping list! Let's find everything.",
    "vo-market-remember": "Can you remember the list?",
    "vo-market-not": "Hmm, is that on our list?",
    "vo-market-pipa": "Now Pipa's list! What does Pipa want?",
    "vo-market-two": "We need two!",
    "vo-market-done": "We found everything! What a lovely shopping trip!",
    "vo-pick-dishes": "Let's wash the dishes!",
    "vo-dishes-start": "Put a dish in the sink!",
    "vo-dishes-scrub": "Scrub, scrub, scrub!",
    "vo-dishes-clean": "Sparkly clean!",
    "vo-dishes-rack": "Now put it on the rack, with the same colour!",
    "vo-dishes-rack-2": "Cups go on the hooks, and plates go below!",
    "vo-dishes-colour": "Find the same colour!",
    "vo-dishes-done": "All clean! Thank you for helping!",
    "name-blue": "Blue!",
    "name-yellow": "Yellow!",
    # Gameplay round 5 (added 2026-09-28; Voice A only: python make_vo.py mom-a <names>): the chef hats on the title
    # (the difficulty), Pipa's order of three, remembering her wish, two kinds in her decorating wish
    "vo-little-chef": "Little chef!",
    "vo-big-chef": "Big chef!",
    "vo-pipa-order-3": "Look! Pipa wants three things, in order. First...",
    "vo-remember": "Can you remember what Pipa wants?",
    "vo-and": "and...",
    # The garden, round 2 (added 2026-09-28; Voice A only: python make_vo.py mom-a <names>): weeds, just enough water,
    # a second cloud, the bunny's wish
    "vo-garden-weeds": "Oh no, weeds! Let's pull them out first!",
    "vo-garden-enough": "That's enough water! Now the next one.",
    "vo-garden-cloud-2": "Another cloud! Push it away too!",
    "vo-garden-bunny": "Here comes a bunny! What does it want to eat?",
    "vo-garden-bunny-this": "The bunny wants this one!",
    "vo-garden-bunny-yum": "Yum! Thank you! The bunny is happy.",
    # The art corner (added 2026-10-02; Voice A only: python make_vo.py mom-a <names>): five kinds of drawing
    "vo-pick-art": "Let's draw together!",
    "vo-art-what": "What shall we draw today?",
    "vo-trace": "Follow the dots with your finger!",
    "vo-trace-done": "You traced it all the way round!",
    "vo-dots": "Let's join the dots!",
    "vo-dots-done": "Look what we made!",
    "vo-colour": "Let's colour it in! Pick a colour.",
    "vo-colour-copy": "Can you colour it like Mom's?",
    "vo-colour-mom": "Hmm, Mom used...",
    "vo-colour-done": "What beautiful colours!",
    "vo-mirror": "Draw on one side, and watch the magic!",
    "vo-mirror-done": "A magic butterfly!",
    "vo-mirror-plate": "A magic party plate!",
    "vo-steam": "Oh, the window is all steamy! Wipe it with your finger.",
    "vo-steam-find": "Can you find the...",
    "vo-steam-done": "Now we can see the whole garden!",
    "name-sun": "Sun!",
    "name-egg": "Egg!",
    "name-fish": "Fish!",
    "name-ball": "Ball!",
    "name-rainbow": "Rainbow!",
    "name-house": "House!",
    "name-tree": "Tree!",
    "name-boat": "Boat!",
    "name-butterfly": "Butterfly!",
    "name-crown": "Crown!",
    "name-bird": "Bird!",
    "name-cat": "Cat!",
    "name-red": "Red!",
    "name-green": "Green!",
    "name-purple": "Purple!",
    "name-orange": "Orange!",
    # The clinic (added 2026-10-03; Voice A only: python make_vo.py mom-a <names>): Mom the nurse
    "vo-pick-clinic": "Let's go to our clinic!",
    "vo-clinic-hello": "Welcome to our clinic! Who shall we help first?",
    "vo-clinic-next": "Who's next?",
    "vo-hi-turtle": "Hello, Turtle! Come in.",
    "vo-hi-penguin": "Hello, Penguin! Come in.",
    "vo-hi-giraffe": "Hello, Giraffe! You're so tall!",
    "vo-hi-pipa": "Pipa! Come in, little one.",
    "vo-sick-fever": "Oh dear, you feel hot! Let's check your temperature.",
    "vo-sick-cough": "Oh, a little cough! Let's listen.",
    "vo-sick-tummy": "A tummy ache? Let's make it better.",
    "vo-sick-tooth": "A sore tooth? Let's have a look.",
    "vo-sick-knee": "Oops, a scraped knee! Let's clean it.",
    "vo-sick-paw": "A splinter in your foot! Let's take it out.",
    "vo-clinic-what": "What's wrong? Look, and listen!",
    "vo-clinic-look": "Hmm, look again!",
    "vo-clinic-plan": "Here's what we need. Can you remember?",
    "vo-clinic-first": "Hmm, what comes first?",
    "vo-clinic-notyet": "Not that one yet!",
    "vo-tool-thermometer": "The thermometer! Hold it in the mouth.",
    "vo-thermo-hot": "A little bit hot!",
    "vo-thermo-ok": "Just right now!",
    "vo-tool-cloth": "A cool cloth for the head.",
    "vo-tool-syrup": "A spoon of yummy medicine!",
    "vo-tool-stethoscope": "Let's listen with the stethoscope.",
    "vo-stetho-find": "Can you find the wheezy spot?",
    "vo-stetho-heart": "Thump, thump! A happy heart!",
    "vo-tool-cup": "A sip of water.",
    "vo-tool-rinse": "Now rinse with water!",
    "vo-tool-hotbottle": "A warm bottle for the tummy.",
    "vo-say-aah": "Say, aah!",
    "vo-tool-toothbrush": "Brush, brush, brush!",
    "vo-tool-spray": "Let's wash it clean.",
    "vo-tool-cream": "A little cream. Rub, rub!",
    "vo-tool-plaster": "And a plaster!",
    "vo-tool-tweezers": "Gently pull it out, with the tweezers.",
    "vo-tool-magnifier": "Where is it? Look with the magnifier!",
    "vo-found-it": "There it is!",
    "vo-clinic-better": "All better!",
    "vo-sticker": "Pick a sticker!",
    "vo-clinic-bye-patient": "Bye bye! Feel better!",
    "vo-clinic-photo": "Let's take a picture of our happy patients!",
    "vo-clinic-done": "You took such good care of everyone!",
    # The clinic, round 2 (added 2026-10-03; Voice A only: python make_vo.py mom-a <names>): itchy spots, a cold, a bell
    "vo-sick-spots": "Oh, itchy spots! Let's make them better.",
    "vo-sick-cold": "Achoo! A sniffly cold.",
    "vo-sick-toy": "Oh my! You swallowed a little bell!",
    "vo-tool-dab": "A dab of cream on every spot!",
    "vo-tool-tissue": "A tissue. Now, a big blow!",
    "vo-tool-warmdrink": "A warm drink. Mmm!",
    "vo-tool-magnet": "The magnet! Pull the bell out.",
    "vo-jingle": "Jingle jingle! There's the bell!",
    "vo-bell-out": "Out it comes! Silly bell!",
    "vo-clinic-bless": "Bless you!",
    # Market and garden, round 3 (added 2026-10-03; Voice A only: python make_vo.py mom-a <names>): a visitor at the
    # stall, a mixed-up box, paying; a rainy day, the scarecrow, the butterfly, tapping the sun
    "vo-market-guest": "What would she like? Look in her bubble!",
    "vo-market-guest-yum": "Mmm! Just what she wanted. Thank you!",
    "vo-market-mixed": "Oops! Something got mixed up in this box. Can you find it?",
    "vo-market-mixed-yes": "Yes! Back to its own box!",
    "vo-market-mixed-more": "There's one more! Look closely.",
    "vo-market-pay": "Time to pay! One coin for every circle.",
    "vo-market-pay-dots": "Time to pay! Find the coins that match the dots.",
    "vo-market-count": "Let's count them!",
    "vo-market-paid": "All paid! Thank you!",
    "vo-garden-rain": "It's a rainy day! Move the rain cloud over the seeds.",
    "vo-garden-rainbow": "Look! A rainbow!",
    "vo-garden-birds": "The birds want our seeds! Let's dress the scarecrow.",
    "vo-garden-hat": "Pick a hat!",
    "vo-garden-shirt": "Now a shirt!",
    "vo-garden-scare-copy": "Can you dress him just like Mom's picture?",
    "vo-garden-scare-look": "Look at Mom's picture again.",
    "vo-garden-shoo": "Shoo, birds! Our seeds are safe.",
    "vo-garden-butterfly": "A butterfly! Help it visit every flower.",
    "vo-garden-butterfly-done": "Thank you, butterfly! Look at all the fruit!",
    "vo-garden-sun-tap": "Tap the sun to help them grow!",
    # The clinic, round 3 (added 2026-10-03; Voice A only: python make_vo.py mom-a <names>): big close-ups, germs, the
    # eye, the ear, the x-ray, in the style of "Doctor Games for kids"
    "vo-sick-eye": "Oh, a sore, itchy eye! Let's take a look.",
    "vo-sick-ear": "An earache? Let's look inside your ear.",
    "vo-tooth-food": "First, let's wash off the food bits!",
    "vo-germs": "Look! Silly germs! Brush them all away!",
    "vo-germ-run": "Hee hee! It ran away!",
    "vo-tool-filler": "A little hole! Let's fill it with a star.",
    "vo-tool-cotton": "Wipe away the tears with the soft cotton.",
    "vo-eye-speck": "Something tiny is in your eye. Take it out with the tweezers!",
    "vo-tool-eyedrops": "Now some drops. Drip, drop!",
    "vo-tool-light": "Shine the light inside. What can you see?",
    "vo-ear-bug": "A tiny ladybug! Gently, take it out.",
    "vo-bug-bye": "Fly away home, little ladybug!",
    "vo-tool-swab": "Now clean the ear with the cotton swab.",
    "vo-tool-icepack": "An ice pack. Nice and cool!",
    "vo-tool-xray": "Let's look inside your tummy with the x-ray!",
    "vo-tummy-germs": "Tummy germs! A drop of medicine on each one.",
    "vo-germs-gone": "Bye bye, germs!",
    "vo-clinic-which": "Which tool do we need now?",
    "vo-knee-dirt": "Let's wash all the dirt off.",
    # the title's two games (clinic round 3): Mom says the card's title when it is tapped
    "vo-world-cooking": "Cooking with Mom!",
    "vo-world-doctor": "Doctor with Mom!",
    # The clinic, round 4 (added 2026-10-04; Voice A only: python make_vo.py mom-a <names>): the children, two problems a
    # patient, the bee sting, the bug bites, the mud; the easy / hard level on the title (no longer chef hats)
    "vo-hi-lily": "Hello, Lily! Come in.",
    "vo-hi-leo": "Hi, Leo! Come on in.",
    "vo-hi-mia": "Hello, little Mia! Come in, sweetie.",
    "vo-hi-sam": "Hi, Sam! In you come.",
    "vo-sick-sting": "Ouch, a bee sting! Let's make it better.",
    "vo-sick-bites": "Oh, itchy bug bites!",
    "vo-sick-dirty": "Oh my, you're all muddy! Let's wash you clean.",
    "vo-tool-sponge": "Scrub, scrub, scrub with the sponge!",
    "vo-tool-bugspray": "Spray the little bugs away!",
    "vo-rinse-foam": "Now rinse off the bubbles!",
    "vo-bugs-bye": "Bye bye, little bugs!",
    "vo-all-clean": "All clean!",
    "vo-clinic-fixfirst": "What shall we fix first?",
    "vo-clinic-fixed": "That's better! Now, what else?",
    "vo-bug-hop": "Hee hee! It hopped away!",
    "vo-level-easy": "Easy!",
    "vo-level-hard": "Hard!",
    # The clinic, round 5 (added 2026-10-09; Voice A only: python make_vo.py mom-a <names>; research/clinic-spec-5.md):
    # eight more patients, the scratchy throat, the sunburn
    "vo-hi-cat": "Hello, Mittens! Come in, kitty.",
    "vo-hi-panda": "Hello, Bao! Come in, little panda.",
    "vo-hi-bunny": "Hi, Clover! Hop on in.",
    "vo-hi-puppy": "Hello, Biscuit! Come in, puppy.",
    "vo-hi-ruby": "Hello, Ruby! Come in.",
    "vo-hi-noah": "Hi, Noah! Come on in.",
    "vo-hi-zoe": "Hello, Zoe! In you come.",
    "vo-hi-max": "Hi, Max! Come on in.",
    "vo-sick-throat": "Ooh, a scratchy throat. Say aah!",
    "vo-sick-sunburn": "Too much sun! Let's cool you down.",
    "vo-tool-honey": "A spoon of honey. Sweet!",
    "vo-tool-aloe": "Cool aloe gel on every red spot.",
    "vo-tool-hat": "A sun hat for next time!",
    "vo-tickles": "Look, little tickles! Spray them away.",
    # The clinic, round 5, more challenge (added 2026-10-09; Voice A only: python make_vo.py mom-a <names>): hide and seek
    # in the waiting room, the germ behind the tongue, the blink with the eye drops
    "vo-hide": "Oh! Someone is hiding! Can you find them?",
    "vo-found-you": "Peekaboo! Found you!",
    "vo-tongue": "One more germ is hiding behind the tongue!",
    "vo-hold-still": "Oops, a blink! Hold it still.",
    # More challenge in the games that are not cooking (added 2026-10-09; Voice A only: python make_vo.py mom-a <names>):
    # the garden, the market, washing up, the art corner (research/challenge-spec.md, PR B)
    "vo-not-ripe": "Not ripe yet! Let the sun help it.",
    "vo-one-more-seed": "And one more!",
    "vo-sort-basket": "Find the basket for the...",
    "vo-find-caterpillar": "Someone is nibbling our leaves! Can you find the little caterpillar?",
    "vo-caterpillar-found": "There you are! Into the jar you go.",
    "vo-caterpillar-bye": "Off you go, little one!",
    "vo-weigh": "Let's weigh them! We need...",
    "vo-too-heavy": "Oops, too heavy!",
    "vo-need-green": "We need something green!",
    "vo-need-tree": "We need a fruit that grows on a tree!",
    "vo-need-round": "We need something round!",
    "vo-is-green": "Hmm, is that green?",
    "vo-is-tree": "Hmm, does that grow on a tree?",
    "vo-is-round": "Hmm, is that round?",
    "vo-big-coin": "That one is for a big coin!",
    "vo-small-coin": "That one is for a small coin!",
    "vo-dry": "Now dry it with the towel!",
    "vo-dry-first": "Let's dry it first!",
    "vo-try-sponge": "Try the sponge!",
    "vo-biggest-first": "The biggest one first!",
    "vo-art-stamps": "Let's stamp a picture!",
    "vo-find-number": "Find...",
    "vo-follow-arrows": "Follow the arrows!",
    "name-cup": "Cup!",
    "name-plate": "Plate!",
    "name-kite": "Kite!",
    "name-ice-cream": "Ice cream!",
    "name-balloon": "Balloon!",
    "name-snail": "Snail!",
    "name-cloud": "Cloud!",
    # Recipe challenges, PR A (added 2026-10-09; Voice A only: python make_vo.py mom-a <names>): soap before rubbing,
    # what goes in first (hard), Mom's oven number (hard), Mom's model in decorating (hard), find the tool in every recipe
    "vo-soap": "Soap first! Rub it on your hands.",
    "vo-pour-first": "Let's start with the...",
    "vo-this-first": "Hmm, not that one yet. First, the...",
    "vo-temp-set": "Let's set the oven to...",
    "vo-like-mine": "Look at my picture! Can you make one like mine?",
    "vo-same-as-mine": "Just like mine!",
    "vo-find-servers": "Where are the salad servers? Can you find them?",
    "vo-find-stick": "Which one is the skewer stick? Can you find it?",
    "name-flour": "Flour!",
    "name-sugar": "Sugar!",
    "name-milk": "Milk!",
    "name-butter": "Butter!",
    "name-servers": "Salad servers!",
    "name-stick": "Skewer stick!",
}
SUFFIX = ""
if len(sys.argv) > 1 and sys.argv[1] in ("mom", "mom-a"):
    if sys.argv[1] == "mom-a":  # Voice A (af_heart) only
        VOICES = {"voice-a": VOICES["voice-a"]}
    LINES, SUFFIX = MOM_LINES, "-mom"
    if len(sys.argv) > 2:  # regenerate only the named lines, e.g. make_vo.py mom vo-bye vo-praise-7
        LINES = {k: v for k, v in LINES.items() if k in sys.argv[2:]}
TARGET_LUFS = -18.0
PEAK_LIMIT = 10 ** (-1.5 / 20)

def trim(x, sr, thresh_db=-42, pre=0.02, post=0.06):
    env = np.abs(x)
    win = int(0.01 * sr)
    env = np.convolve(env, np.ones(win) / win, mode="same")
    thr = env.max() * 10 ** (thresh_db / 20)
    idx = np.where(env > thr)[0]
    a = max(0, idx[0] - int(pre * sr)); b = min(len(x), idx[-1] + int(post * sr))
    y = x[a:b].copy()
    fi, fo = int(0.005 * sr), int(0.04 * sr)
    y[:fi] *= np.linspace(0, 1, fi); y[-fo:] *= np.linspace(1, 0, fo)
    return y

def loudness(y, sr):
    meter = pyln.Meter(sr, block_size=min(0.4, len(y) / sr * 0.9))
    return meter.integrated_loudness(np.concatenate([y, y, y]))  # tile very short clips for stable gating

kok = Kokoro(str(ROOT / "tools/kokoro/kokoro-v1.0.onnx"), str(ROOT / "tools/kokoro/voices-v1.0.bin"))
report = []
for folder, (voice, speed) in VOICES.items():
    folder += SUFFIX
    (ROOT / folder).mkdir(exist_ok=True)
    for name, text in LINES.items():
        audio, sr = kok.create(text, voice=voice, speed=speed, lang="en-us")
        audio = np.asarray(audio, dtype=np.float64)
        sf.write(ROOT / f"work/vo/{folder}-{name}-raw.wav", audio, sr)
        y = trim(audio, sr)
        gain = 10 ** ((TARGET_LUFS - loudness(y, sr)) / 20)
        y = y * gain
        pk = np.abs(y).max()
        if pk > PEAK_LIMIT:
            y *= PEAK_LIMIT / pk
        wav = ROOT / f"work/vo/{folder}-{name}.wav"
        sf.write(wav, y, sr, subtype="PCM_16")
        out = ROOT / folder / f"{name}.ogg"
        subprocess.run([str(FFMPEG), "-y", "-loglevel", "error", "-i", str(wav), "-c:a", "libvorbis", "-q:a", "3", "-ac", "1", str(out)], check=True)
        report.append((folder, name, round(len(y) / sr, 2), round(loudness(y, sr), 1), out.stat().st_size))
        print(report[-1], flush=True)
rep_path = ROOT / f"work/vo/report{SUFFIX}.json"
old = json.load(open(rep_path)) if rep_path.exists() and len(sys.argv) > 2 else []
done = {(f, n) for f, n, *_ in report}
report = [r for r in old if (r[0], r[1]) not in done] + [[f, n, d, float(l), z] for f, n, d, l, z in report]
json.dump(report, open(rep_path, "w"), indent=1)
